export const comments = [
  {
    author: "Insight Master",
    nickname: "@TruePerspective",
    avatarUrl: "/home/comments/avatar_1.png",
    text: "The product offers reliable performance and is well-suited for long-term use. However, improvements in user experience could elevate its value significantly.",
    post_time: "5:48 PM",
    post_date: "Sep 15, 2021",
  },
  {
    author: "Informed Opinion",
    nickname: "@QualityCheck",
    avatarUrl: "/home/comments/avatar_2.png",
    text: "Astra Finance offers unparalleled security features that make it a trustworthy platform for all transactions. Highly recommend for those prioritizing safety.",
    post_time: "5:48 PM",
    post_date: "Sep 15, 2021",
  },
  {
    author: "Expert Reviewer",
    nickname: "@TrustedInsight",
    avatarUrl: "/home/comments/avatar_3.png",
    text: "As an industry professional, I appreciate the attention to detail. That said, expanding the feature set could make this solution more competitive.",
    post_time: "6:43 PM",
    post_date: "Sep 15, 2021",
  },
  {
    author: "Credible Source",
    nickname: "@VerifiedOpinion",
    avatarUrl: "/home/comments/avatar_4.png",
    text: "Thoroughly tested this service, and while the core functionality works well, there's room for enhancement in terms of efficiency and customer support.",
    post_time: "6:43 PM",
    post_date: "Sep 15, 2021",
  },
  {
    author: "Insight Master",
    nickname: "@TruePerspective",
    avatarUrl: "/home/comments/avatar_1.png",
    text: "The product offers reliable performance and is well-suited for long-term use. However, improvements in user experience could elevate its value significantly.",
    post_time: "5:48 PM",
    post_date: "Sep 15, 2021",
  },
  {
    author: "Credible Source",
    nickname: "@VerifiedOpinion",
    avatarUrl: "/home/comments/avatar_4.png",
    text: "Thoroughly tested this service, and while the core functionality works well, there's room for enhancement in terms of efficiency and customer support.",
    post_time: "6:43 PM",
    post_date: "Sep 15, 2021",
  },
];
