import type { Metadata } from "next";
import Providers from "./Providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { AppKit } from "@/context/web3modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AppKit>
        <Providers>
          <Header />
          <main> {children}</main>
          <Footer />
        </Providers>
        </AppKit>
      </body>
    </html>
  );
}
